### ISSUE TITLE
About Demo

### ISSUE THREAD

**Issue by CaineGu** [diffFacto/diffFacto#2]
We are really excited to find your work uploaded. When I try to use the demo you provided, I got an error as follow:
`FileNotFoundError: [Errno 2] No such file or directory: '/orion/u/w4756677/datasets/diffFacto_data/train_test_split/shuffled_train_file_list.json'`

however, I don't have a folder /orion/ 
after i change the code at line 76 in shapenet_seg.py to my absolute path, the problem still occur.
could you plz help me with some tips
Thanks a lot

**Comment by QiXingRan** [comment]
hi，you'd better try to change the '/orion/u/w4756677/datasets/diffFacto_data/train_test_split/shuffled_train_file_list.json' to your own diffFacto_data in /configs/gen_chair.py 107 & 121 lines
