### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by QiXingRan** [diffFacto/diffFacto#3]
I found in the python/diffFacto datasets directory is used to evaluate model performance function.After I run the code, I get an npz file, which contains multiple npy files. Could you please tell me the related purposes of each file

**Comment by georgeNakayama** [comment]
Hi @QiXingRan, Thanks for the question! The npz file contains the following: 

"x_sample 0": generated shape at diffusion shape step x

"sample prior 0": the starting position of the cross diffusion

"pred_sample 0" = "pred":  The generated shapes

"pred_seg_mask" = generated segmentation mask for the shapes

"anchors" = the regressed means for each of semantic part of the generated shape. 

"input", "input_ref", "ref_seg_mask", "present", "shift", "scale": not used during generation

Let me know if you have any questions
