### ISSUE TITLE
Cannot Run The Training Script

### ISSUE THREAD

**Issue by ardianumam** [diffFacto/diffFacto#4]
Hi,

Thanks for the awesome work! 

1. I tried to run the training script, but I got this error: `AttributeError: 'Runner' object has no attribute 'run'`. Seems like `runner.run()` in [this line](https://github.com/diffFacto/diffFacto/blob/2b7e09b780d3139ad0dd86e53ee56ece5198aa81/tools/run_net.py#L113) should be `runner.train()`? 
2. What is the purpose of having two stages of the training? I cannot find the related explanation in the paper

Thanks

**Comment by georgeNakayama** [comment]
Hi @ardianumam  Thanks for the questions. 

1. This is a strange error. I didn't get it on my side. The Runner class should have a run method at [here]( https://github.com/diffFacto/diffFacto/blob/main/python/difffacto/runner/runner.py#L143 ). Can you provide more details about the error? Thanks! 

2. The implementation detail is in the Supplementary, see section S5.1 of Supplementary.
